# Generated by Django 4.2.2 on 2023-07-05 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='name',
            new_name='first_name',
        ),
    ]
