# Generated by Django 4.2.2 on 2023-07-02 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobpost_date_jobpost_description_jobpost_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
